/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import cloudBox.CloudFile;
import cloudBox.FileInterfaceForResource;
import cloudBox.User;
import java.io.File;
import java.rmi.RemoteException;
import javax.swing.JFileChooser;

public class FrameAdmFile extends javax.swing.JFrame {

    private FileInterfaceForResource resource;
    private User user;
    
    public FrameAdmFile(FileInterfaceForResource srv, String userName) throws RemoteException {
        initComponents();
        
        user = srv.getUser(userName);
        
        this.resource = srv;
        maJTableFileAdministration1.setData(user.getListFile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maJTableFileAdministration1 = new MaJTableFile();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jMenuItem1.setText("Add file");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Remove file");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Quit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maJTableFileAdministration1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(maJTableFileAdministration1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser choiceFile = new JFileChooser();
        int returnVal = choiceFile.showOpenDialog(choiceFile);
        
        File file;
        
        try {
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = choiceFile.getSelectedFile();
                CloudFile newFile = new CloudFile(user.getName(), file.getName());
                user.addFile(newFile);
                resource.addFile(user.getName(), newFile);
                maJTableFileAdministration1.setData(user.getListFile());
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private MaJTableFile maJTableFileAdministration1;
    // End of variables declaration//GEN-END:variables
}
