/*
 * Copyright (C) 2013 Zirani J.-L.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as 
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cloudbox.module.gui;

import cloudbox.module.file.FileModule;
import cloudbox.module.network.NetModule;
import java.awt.Component;
import java.awt.Container;
import java.io.File;
import java.util.Properties;
import javax.swing.JDialog;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
/**
 *
 * @author Zirani J.-L.
 */
public class OptionFrame extends JDialog {

    private Properties m_properties;
    private MainFrame m_mainFrame;
    static private String ms_filePackage = FileModule.class.getPackage().getName();
    static private String ms_netPackage = NetModule.class.getPackage().getName();
    
    /**
     * Creates new form OptionFrame
     */
    public OptionFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public OptionFrame(MainFrame f_mainFrame, Properties f_properties) {
        super();
        initComponents();
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setTitle("Option");
        m_properties = f_properties;
        enableComponents(athPanel, enabledCheckBox.isSelected());
        m_mainFrame = f_mainFrame;
    }

    
    public void enableComponents(Container container, boolean bEnable) {
        container.setEnabled(bEnable);
        Component[] components = container.getComponents();
        for (Component component : components) {
            if (component instanceof Container) {
                enableComponents((Container)component, bEnable);
            }
            else {
                component.setEnabled(bEnable);
            }
        }
    }
    
    public void setProperties() {
        switch(m_properties.getProperty(ms_netPackage+".mode", "client")) {
            case "server" : setServerProp(); break;
            default: setClientProp();
        }
        
        directoryField.setText(m_properties.getProperty(
                ms_filePackage + ".directory", 
                System.getProperty("user.home")+File.separator+"CloudBox"+
                File.separator));
    }
    
    private void setClientProp() {
        clientMode.setSelected(true);
        setClientPanel();
        hostField.setText(m_properties.getProperty(ms_netPackage+".server", "localhost"));
        portField.setText(m_properties.getProperty(ms_netPackage+".port", "1337"));
    }

    private void setServerProp() {
        serverMode.setSelected(true);
        setServerPanel();
        portField.setText(m_properties.getProperty(ms_netPackage+".port", "1337"));
    }
    
    
    public final void setServerPanel() {
        networkPanel.setBorder(BorderFactory.createTitledBorder("Server")); 
        hostField.setEnabled(false);
    }
    
    public final void setClientPanel() {
        networkPanel.setBorder(BorderFactory.createTitledBorder("Client")); 
        hostField.setEnabled(true);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeGroup = new javax.swing.ButtonGroup();
        directoryChooser = new javax.swing.JFileChooser();
        generalPanel = new javax.swing.JPanel();
        modeLabel = new javax.swing.JLabel();
        serverMode = new javax.swing.JRadioButton();
        clientMode = new javax.swing.JRadioButton();
        dirLabel = new javax.swing.JLabel();
        directoryField = new javax.swing.JTextField();
        directoryChooserButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enabledCheckBox = new javax.swing.JCheckBox();
        networkPanel = new javax.swing.JPanel();
        portLabel = new javax.swing.JLabel();
        portField = new javax.swing.JFormattedTextField();
        hostLabel = new javax.swing.JLabel();
        hostField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        applyButton = new javax.swing.JButton();
        athPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();

        directoryChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        generalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));

        modeLabel.setText("Mode :");

        modeGroup.add(serverMode);
        serverMode.setText("Server");
        serverMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverModeActionPerformed(evt);
            }
        });

        modeGroup.add(clientMode);
        clientMode.setSelected(true);
        clientMode.setText("Client");
        clientMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientModeActionPerformed(evt);
            }
        });

        dirLabel.setText("Directory :");

        directoryChooserButton.setText("change");
        directoryChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryChooserButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Athentification:");

        enabledCheckBox.setText("Enable");
        enabledCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enabledCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enabledCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(modeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverMode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientMode)
                        .addContainerGap())
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addComponent(dirLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryChooserButton))))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeLabel)
                    .addComponent(serverMode)
                    .addComponent(clientMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dirLabel)
                    .addComponent(directoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directoryChooserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enabledCheckBox)))
        );

        networkPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Server"));

        portLabel.setText("port :");

        portField.setText("1337");

        hostLabel.setText("Host address:");

        hostField.setText("localhost");

        javax.swing.GroupLayout networkPanelLayout = new javax.swing.GroupLayout(networkPanel);
        networkPanel.setLayout(networkPanelLayout);
        networkPanelLayout.setHorizontalGroup(
            networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPanelLayout.createSequentialGroup()
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hostLabel)
                    .addComponent(portLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        networkPanelLayout.setVerticalGroup(
            networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPanelLayout.createSequentialGroup()
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hostLabel)
                    .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portLabel)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        athPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Authentification"));

        jLabel2.setText("User name:");

        jLabel3.setText("Password:");

        jTextField1.setText("jTextField1");

        jPasswordField1.setText("jPasswordField1");

        jLabel4.setText("Confirm password:");

        jPasswordField2.setText("jPasswordField2");

        javax.swing.GroupLayout athPanelLayout = new javax.swing.GroupLayout(athPanel);
        athPanel.setLayout(athPanelLayout);
        athPanelLayout.setHorizontalGroup(
            athPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1))
            .addGroup(athPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1))
            .addGroup(athPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2))
        );
        athPanelLayout.setVerticalGroup(
            athPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(athPanelLayout.createSequentialGroup()
                .addGroup(athPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(athPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(athPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(applyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
            .addComponent(athPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(networkPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(generalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(networkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(athPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(applyButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void directoryChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryChooserButtonActionPerformed
        File curDir = new File(directoryField.getText());
        
        if(!curDir.exists() || !curDir.isDirectory()) { 
            directoryField.setText( System.getProperty("user.home")+
                    File.separator+ "CloudBox"+ File.separator);
            curDir =  new File( directoryField.getText() );
        }

        directoryChooser.setCurrentDirectory(curDir);
        //directoryChooser.showOpenDialog(this);
        
        if(directoryChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = directoryChooser.getSelectedFile();
            if(selectedFile.exists() && selectedFile.isDirectory()) {
                directoryField.setText(selectedFile.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_directoryChooserButtonActionPerformed

    private void clientModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientModeActionPerformed
        setClientPanel();
    }//GEN-LAST:event_clientModeActionPerformed

    private void serverModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverModeActionPerformed
        setServerPanel();
    }//GEN-LAST:event_serverModeActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        applyButtonActionPerformed(evt);
                   
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        
        if(serverMode.isSelected()) {
            m_properties.setProperty(ms_netPackage+".mode", "server"); 
            m_properties.remove(ms_netPackage+".server");
        }
        else {   
            m_properties.setProperty(ms_netPackage+".mode", "client"); 
            m_properties.setProperty(ms_netPackage+".server", hostField.getText());
        }
        
        m_properties.setProperty(ms_netPackage+".port", portField.getText());
        m_properties.setProperty(FileModule.class.getPackage().getName()+".directory", directoryField.getText());
        m_mainFrame.updateServices();
    }//GEN-LAST:event_applyButtonActionPerformed

    private void enabledCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enabledCheckBoxActionPerformed
        enableComponents(athPanel, enabledCheckBox.isSelected());
    }//GEN-LAST:event_enabledCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel athPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton clientMode;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JFileChooser directoryChooser;
    private javax.swing.JButton directoryChooserButton;
    private javax.swing.JTextField directoryField;
    private javax.swing.JCheckBox enabledCheckBox;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JTextField hostField;
    private javax.swing.JLabel hostLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.ButtonGroup modeGroup;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JPanel networkPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JFormattedTextField portField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JRadioButton serverMode;
    // End of variables declaration//GEN-END:variables


}
